tags:
  - name: Remembrances
    description: '추모 관련 API'
  - name: Comments
    description: '추모글 관련 API'
  - name: Obituaries
    description: '부고 관련 API'

components:
  schemas:
    Remembrance:
      type: object
      required:
      - userId
      - fullName
      - dateOfBirth
      properties:
        _id:
          type: string
          description: '추모 objectId'
          example: '62d05d9f1eed1cb973a7f36c'
        userId:
          type: string
          description: '유저 objectId'
          example: '62c7d6d0aa14441e00d23232'
        fullName:
          type: string
          description: '회원 이름'
          example: '홍길동'
        dateOfBirth:
          type: string
          description: '회원 태어난 날짜'
          example: '1999-01-01'
        dateOfDeath:
          type: string
          description: '회원 사망 날짜'
          example: '2099-01-01'
        isPublic:
          type: boolean
          description: '추모 공개 여부'
          example: true
        photo:
          type: string
          description: '회원 영정 사진 url'
    RemembranceWithCommentId:
      allOf:
      - $ref: "#/components/schemas/Remembrance"
      - type: object
        properties:
          comments:
            type: array
            items:
              $ref: "#/components/schemas/Comment/properties/_id"
            description: '추모글 id 배열'
    Comment:
      type: object
      required:
      - writer
      - title
      - content
      - password
      properties:
        _id:
          type: string
          description: '추모글 objectId'
          example: '62d0661abd3ff204df02a869'
        writer:
          type: string
          description: '추모글 작성자'
          example: '김철수'
        title:
          type: string
          description: '추모글 제목'
          example: '보고싶어요'
        content:
          type: string
          description: '추모글 내용'
          example: '그립습니다.'
        password:
          type: string
          description: '추모글 비밀번호'
    Obituary:
      type: object
      required:
        - deceased
        - dateOfBirth
        - dateOfDeath
        - age
        - sex
        - family
        - funeral
        - password
      properties:
        _id:
          type: string
          description: '부고 objectId'
          example: '62d567dfd4d86996e6973c9e'
        deceased:
          type: string
          description: '고인 이름'
          example: '홍길동'
        dateOfBirth:
          type: string
          format: date
          description: '고인 탄생일'
          example: '1999-12-30'
        dateOfDeath:
          type: string
          format: date
          description: '고인 사망일 : 탄생일 ~ 오늘날짜 사이 값'
          example: '2022-01-01'
        age:
          type: number
          description: '고인 나이'
          example: 100
        sex:
          type: string
          enum: ['남자', '여자']
          description: '고인 성별'
          example: '남자'
        family:
          type: array
          items:
            $ref: "#/components/schemas/Family"
          description: '상주 리스트'
        funeral:
          type: string
          description: '장례식장 주소'
          example: '하늘시 어디구 행복동 편안장례식장'
        dateOfCremate:
          type: string
          format: date
          description: '발인 날짜: 사망일 이후 날짜'
          example: '2099-01-04'
        comment:
          type: string
          description: '전할 말'
        password:
          type: string
          description: '부고 비밀번호'
          example: 'qwerty'
    ObituaryCreate:
      type: object
      required:
        - deceased
        - dateOfBirth
        - dateOfDeath
        - sex
        - family
        - funeral
        - password
      properties:
        deceased:
          type: string
          description: '고인 이름'
          example: '홍길동'
        dateOfBirth:
          type: string
          format: date
          description: '고인 탄생일'
          example: '1999-12-30'
        dateOfDeath:
          type: string
          format: date
          description: '고인 사망일 : 탄생일 ~ 오늘날짜 사이 값'
          example: '2022-01-01'
        sex:
          type: string
          enum: ['남자', '여자']
          description: '고인 성별'
          example: '남자'
        family:
          type: array
          items:
            $ref: "#/components/schemas/Family"
          description: '상주 리스트'
        funeral:
          type: string
          description: '장례식장 주소'
          example: '하늘시 어디구 행복동 편안장례식장'
        dateOfCremate:
          type: string
          format: date
          description: '발인 날짜: 사망일 이후 날짜'
          example: '2099-01-04'
        comment:
          type: string
          description: '전할 말'
        password:
          type: string
          description: '부고 비밀번호'
          example: 'qwerty'
    ObituaryUpdate:
      type: object
      required:
        - password
      properties:
        deceased:
          type: string
          description: '고인 이름'
          example: '홍길동'
        dateOfBirth:
          type: string
          format: date
          description: '고인 탄생일'
          example: '1999-12-30'
        dateOfDeath:
          type: string
          format: date
          description: '고인 사망일 : 탄생일 ~ 오늘날짜 사이 값'
          example: '2022-01-01'
        sex:
          type: string
          enum: ['남자', '여자']
          description: '고인 성별'
          example: '남자'
        family:
          type: array
          items:
            $ref: "#/components/schemas/Family"
          description: '상주 리스트'
        funeral:
          type: string
          description: '장례식장 주소'
          example: '하늘시 어디구 행복동 편안장례식장'
        dateOfCremate:
          type: string
          format: date
          description: '발인 날짜: 사망일 이후 날짜'
          example: '2099-01-04'
        comment:
          type: string
          description: '전할 말'
        password:
          type: string
          description: '부고 비밀번호'
          example: 'qwerty'
    Family:
      type: object
      required:
      - relation
      - fullName
      properties:
        relation:
          type: string
          description: '고인과의 관계'
          example: '장남'
        fullName:
          type: string
          description: '상주 이름'
          example: '홍철수'
  parameters:
    remembranceIdParam:
      name: remembranceId
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/Remembrance/properties/_id"
    commentIdParam:
      name: commentId
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/Comment/properties/_id"
    obituaryIdParam:
      name: obituaryId
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/Obituary/properties/_id"
  requestBodies:
    commentReq:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              writer:
                $ref: "#/components/schemas/Comment/properties/writer"
              title:
                $ref: "#/components/schemas/Comment/properties/title"
              content:
                $ref: "#/components/schemas/Comment/properties/content"
              password:
                $ref: "#/components/schemas/Comment/properties/password"
  responses:
    deleteRes:
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                type: string
                example: "success"
    remembrancesRes:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/RemembranceWithCommentId"
    remembranceRes:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RemembranceWithCommentId"
    remembranceWithCommentsRes:
      content:
        application/json:
          schema:
            allOf:
            - $ref: "#/components/schemas/Remembrance"
            - type: object
              properties:
                comments:
                  type: array
                  items:
                    $ref: "#/components/schemas/Comment"
                  description: '추모글 배열'
    commentRes:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Comment"
    obituaryRes:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Obituary"

paths:
  /api/remembrances:
    get:
      tags:
      - Remembrances
      summary: "전체 추모 데이터 조회"
      description: "전체 사망한 유저의 추모 데이터를 최근 업데이트된 순으로 조회"
      responses:
        200:
          description: "여러개의 추모 데이터 조회"
          $ref: "#/components/responses/remembrancesRes"
  /api/remembrances/recent?count={count}:
    get:
      tags:
      - Remembrances
      summary: "최신 추모 데이터 조회"
      description: "최근 업데이트된 추모 데이터를 count(default 8) 개수만큼 조회"
      parameters:
      - name: count
        in: query
        schema:
          type: number
          description: 가져올 데이터의 개수
          example: 8
      responses:
        200:
          description: "여러개의 추모 데이터 조회"
          $ref: "#/components/responses/remembrancesRes"
  /api/remembrances/{remembranceId}:
    get:
      tags:
      - Remembrances
      summary: "특정 추모 데이터 조회"
      description: "remembranceId로 특정 추모 데이터 조회"
      parameters:
      - $ref: "#/components/parameters/remembranceIdParam"
      responses:
        200:
          description: "하나의 추모 데이터 조회"
          $ref: "#/components/responses/remembranceWithCommentsRes"
  /api/remembrances/{remembranceId}/comments:
    post:
      tags:
      - Comments
      summary: "추모글 생성"
      description: "remembrancId로 추모 데이터 조회 후 추모글 추가"
      parameters:
      - $ref: "#/components/parameters/remembranceIdParam"
      requestBody:
        $ref: "#/components/requestBodies/commentReq"
      responses:
        201:
          description: "추모글 생성"
          $ref: "#/components/responses/commentRes"
  /api/remembrances/{remembranceId}/comments/{commentId}:
    get:
      tags:
      - Comments
      summary: "특정 추모글 조회"
      description: "remembranceId와 commentId로 특정 추모의 특정 추모글 조회"
      parameters:
      - $ref: "#/components/parameters/remembranceIdParam"
      - $ref: "#/components/parameters/commentIdParam"
      responses:
        200:
          description: "하나의 추모글 조회"
          $ref: "#/components/responses/commentRes"
    patch:
      tags:
      - Comments
      summary: "추모글 수정"
      description: "remembranceId와 commentId로 추모글 조회 후 수정"
      parameters:
      - $ref: "#/components/parameters/remembranceIdParam"
      - $ref: "#/components/parameters/commentIdParam"
      requestBody:
        $ref: "#/components/requestBodies/commentReq"
      responses:
        200:
          description: "추모글 수정"
          $ref: "#/components/responses/commentRes"
    delete:
      tags:
      - Comments
      summary: "추모글 삭제"
      description: "remembranceId와 commentId로 추모글 조회 후 삭제"
      parameters:
      - $ref: "#/components/parameters/remembranceIdParam"
      - $ref: "#/components/parameters/commentIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  $ref: "#/components/schemas/Comment/properties/password"
      responses:
        201:
          description: "추모글 데이터 삭제"
          $ref: "#/components/responses/deleteRes"
  /api/obituaries:
    post:
      tags:
      - Obituaries
      summary: "부고 데이터 생성"
      description: "사망자 정보 및 장례식장 정보 등을 입력받아 부고 데이터 생성"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ObituaryCreate"
      responses:
        201:
          description: "부고 데이터 생성"
          $ref: "#/components/responses/obituaryRes"
  /api/obituaries/{obituaryId}:
    get:
      tags:
      - Obituaries
      summary: "특정 부고 데이터 조회"
      description: "부고 objectId를 이용해 특정 부고 데이터 조회"
      parameters:
      - $ref: "#/components/parameters/obituaryIdParam"
      responses:
        200:
          description: "하나의 부고 데이터 조회"
          $ref: "#/components/responses/obituaryRes"
    patch:
      tags:
      - Obituaries
      summary: "부고 데이터 수정"
      description: "objectId를 이용해 부고 데이터 조회 후 일부 수정"
      parameters:
      - $ref: "#/components/parameters/obituaryIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ObituaryUpdate"
      responses:
        201:
          description: "부고 데이터 일부 수정"
          $ref: "#/components/responses/obituaryRes"
    delete:
      tags:
      - Obituaries
      summary: "부고 데이터 삭제"
      description: "objectId를 이용해 부고 데이터 조회 수 삭제"
      parameters:
      - $ref: "#/components/parameters/obituaryIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  $ref: "#/components/schemas/Obituary/properties/password"
      responses:
        201:
          description: "부고 데이터 삭제"
          $ref: "#/components/responses/deleteRes"
